### ISSUE TITLE
🔷 [Epic] Enhance Component Documentation

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#1512]
Description

Resources
(Relevant documentation, Figma links, and other reference material)

```[tasklist]
### Tasks
- [x] [DOC]
- [x] Ensure all core components are accounted for
- [x] add tooling documentation (VSCode, BOS Loader, etc.)
- [x] BOS reference Docs live in the respective repo
- [x] Sync auto-generated BOS docs to docs.near.org
- [x] add documentation for interacting with Ethereum (Ethers.JS)
```
