### ISSUE TITLE
🔹[EPIC]  Migrate tool & library reference docs to their repo

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#1542]
### Description

Migrate library and tooling reference documentation from docs.near.org to their respective repository as the one source of truth. _(ex: near-api-js, near-cli, near-sdk-js, etc.)_ 

Having docs.near.org host all reference documentation, code examples, & snippets is not scalable and can quickly become outdated with new releases. Having documentation reside in the tool/library's repo allows for documentation accuracy checks when new versions are released and follows best practices. 

docs.near.org becomes "flight traffic control" for these tools/libraries, but still hosts more in-depth tutorials and ultimately extracts code snippets dynamically from the repository as it updates. 

---

### Goal

- [ ] Migrate all reference documentation & small snippets to their respective repository
- [ ] Create documentation TDD flows that require passing tests before new version releases

---

### Resources

(Relevant documentation, Figma links, and other reference material)

- Item 1
- Item 2
- Item 3

---

```[tasklist]
### Related Issues
- [ ] https://github.com/near/docs/issues/1576
```
