### ISSUE TITLE
🔹[EPIC] Migrate wiki.near.org to docs

### ISSUE THREAD

**Issue by bucanero** [near/docs#1687]
### Description

`wiki.near.org` needs to be deprecated and useful technical content migrated to `docs.near.org`

---

### Goal

From Illia's feedback:

> Let’s merge content and remove it. It never became a community type thing as initially planned.
It will make sense to just have more content pages on near.org later but most should go to docs.

---

### Resources

(Relevant documentation, Figma links, and other reference material)

- https://github.com/near/wiki
- https://wiki.near.org/

---

```[tasklist]
### Related Issues
- [ ] https://github.com/near/docs/issues/1691
- [x] Flag outdated content and non-technical articles that won't be migrated to docs.near.org
- [x] Define placement for wiki content on Docs
- [x] Migrate tech articles to Docs
- [x] Sunset wiki, redirect site, archive repository
```
