### ISSUE TITLE
🔹[EPIC] Migrate documentation and examples to RS SDK 5.0.0

### ISSUE THREAD

**Issue by gagdiez** [near/docs#1744]
### Description

[NEAR SDK RS 5.0.0 has been released](https://github.com/near/near-sdk-rs/releases/tag/near-sdk-v5.0.0), we now need to update all docs and docs

```[tasklist]
### Related Issues
- [ ] https://github.com/near/docs/issues/1745
- [ ] https://github.com/near/docs/issues/1746
- [x] https://github.com/near/docs/issues/1747
- [x] https://github.com/near/docs/issues/1756
- [x] https://github.com/near/docs/issues/1755
- [x] https://github.com/near/docs/issues/1754
- [x] https://github.com/near/docs/issues/1753
- [x] https://github.com/near/docs/issues/1752
- [x] https://github.com/near/docs/issues/1751
- [x] https://github.com/near/docs/issues/1750
- [x] https://github.com/near/docs/issues/1749
- [x] https://github.com/near/docs/issues/1748
```

**Comment by flmel** [comment]
For integrations tests on the examples  do you think we should be going with javascript/ava or follow the cargo near structure ant test with near_workspaces?

**Comment by gagdiez** [comment]
@flmel sorry for never answering. I guess a good compromise is: workspaces-js for JS projects, workspaces-rs for RS projects

**Comment by mikedotexe** [comment]
Looks like there are some nice changes to reflect. I love how they have the scrolling "before" and "after" here:
https://github.com/near/near-sdk-rs/releases/tag/near-sdk-v5.1.0

Here's an example showing how to use the `#[near]` macro:
https://github.com/NEAR-DevHub/neardevhub-contract/pull/103/files#diff-0138e1668433cf4b746a3d18b143e0a7bd1465d8f67989f7956f52076298b259R14

Think we can simplify stuff like this (and elsewhere)

<img width="931" alt="Screenshot 2024-05-03 at 10 06 06 AM" src="https://github.com/near/docs/assets/1042667/c6ccae67-bbc9-467e-9fec-62840dfaa190">

https://docs.near.org/sdk/rust/contract-structure/near-bindgen

**Comment by flmel** [comment]
Thanks @mikedotexe addressing it!
