### ISSUE TITLE
🔷 [Epic]  Automatize Near Certified Developer Program

### ISSUE THREAD

**Issue by charleslavon** [near/docs#1766]
## Description
Web developers generally arrive with no knowledge on how to create smart contracts, which are a cornerstone of Web3 Apps. In the past, we had NEAR Foundation run the NCD (Near Certified Developer) program, in which people was trained on how to build NEAR Apps, and then evaluated.

The NCD served two purposes: (1) Train people on NEAR Technologies, and (2) Certify developers so companies could then know which talent was available. 

The problem with the NCD is that educating people takes a lot of time, and then evaluating them takes even longer. Because of this the program had to be restarted 2 or 3 times, until it was eventually abandoned.

This EPIC tries to revive the NCD by implementing automatic tools of teaching and evaluation. In practice, we will implement a frontend in which people can learn about NEAR Tech, and a backend that people can use to evaluate the applications they build.

## Resources
1. Main backend project: https://github.com/flmel/evaluator

```[tasklist]
### Tasks
- [ ] https://github.com/flmel/evaluator/issues/6
- [ ] https://github.com/flmel/evaluator/issues/7
- [ ] https://github.com/flmel/evaluator/issues/8
- [ ] https://github.com/flmel/evaluator/issues/9
- [ ] https://github.com/flmel/evaluator/issues/10
- [ ] https://github.com/flmel/evaluator/issues/11
- [ ] https://github.com/flmel/evaluator/issues/12
- [ ] https://github.com/flmel/evaluator/issues/13
- [ ] https://github.com/flmel/evaluator/issues/14
- [ ] https://github.com/flmel/evaluator/issues/15
```
