### ISSUE TITLE
[DOC] add BTC example to Chain Signatures `Build` doc

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#1806]
@Pessina created a BTC example using Chain Signatures that should be added to our Chain Signatures `Build` documentation
https://github.com/Pessina/near-sandbox/blob/main/utils/chain/Bitcoin.tsx

```[tasklist]
### Tasks
- [x] Add this example to https://github.com/near-examples/near-multichain
- [x] Use code from example repo to populate `BTC` tab in Chain Signature's `Build` docs
- [x] Add link to example to `info` tab on `Build`
```
