### ISSUE TITLE
🔹[EPIC] Github-pages for all examples

### ISSUE THREAD

**Issue by gagdiez** [near/docs#1882]
### Description

All of our examples would benefit from having a github page wehre to showcase then

---

```[tasklist]
### Related Issues
- [ ] https://github.com/near/docs/issues/1883
- [ ] https://github.com/near/docs/issues/1884
- [ ] https://github.com/near/docs/issues/1885
- [ ] https://github.com/near/docs/issues/1886
- [ ] https://github.com/near/docs/issues/1887
```

**Comment by gagdiez** [comment]
All examples now have a github page

- https://near-examples.github.io/hello-near-examples/
- https://near-examples.github.io/counters/
- https://near-examples.github.io/guest-book-examples/
- https://near-examples.github.io/donation-examples/
- https://near-examples.github.io/coin-flip-examples/
-
