### ISSUE TITLE
[EPIC] Improve folder structure

### ISSUE THREAD

**Issue by gagdiez** [near/docs#1888]
Currently, the pages URL are not consistent with the `./docs` folder structure, this is getting worst and worst as times passes by, making it hard to maintain docs.

We need to move all files to make them correspond to their URLs. 
```[tasklist]
### Tasks
- [x] Re-organize docs folder structure
- [x] Create redirects for all broken links
- [x] Make sure to not lose translations (e.g. Korean translation)
```
