### ISSUE TITLE
🔹[EPIC] Improvements to Multichain Gas Relayer Docs for Mainnet Launch

### ISSUE THREAD

**Issue by ravigautham** [near/docs#1967]
**Is your feature request related to a problem? Please describe.**
We are working towards a Mainnet launch for the Multichain Gas Relayer in June (along with Chain Signatures), and there are some enhancements we can make to the documentation.

**Describe the solution you'd like**

- [x] We should create a new page that provides a holistic overview of the Multichain Gas Relayer, this would involve a brief description and an up-to-date technical design diagram. Right now it is confusing to only have pages for the separate components of the system. 

- [x] Under the Multichain Gas Relayer section in the navigation menu we should move "Multichain Gas Station" to be the first item and rename it to be "Multichain Gas Station Contract". The contract is the first component that a developer would interact with

On the Multichain Relayer Server page we should make the following changes:

- [x] Improved visual of technical system design diagram, would it be possible to recreate this to make the components more visible  and we can move this diagram to the new section I described above ^
- [x] For the "Paymaster" section we need to add more details on the number of paymaster accounts that developers need to create and fund on destination chains. We need to highlight that having multiple paymaster accounts and rotating through them will be important for avoiding issues with nonces on destination chains. @encody Is there any specific process/guidelines we can provide devs on determining the number of paymaster addresses required? Does it scale with the number of transactions/users?
- [ ] In the "System Workflow" section we need to update the "canhazgas.testnet" to reference the specific mainnet contract that a developer deploys (In step 1.ii)
- [x] Add a deeplink to the settlement section in step 6. for "Cross Chain Settlement"

On the Multichain Gas Station Contract page we should make the following changes:

- [ ] In the gas fee estimation section, we reference BSC chain specifically but make no reference to other chains like ETH. We should add more context here. Maybe we can create a table that lists all supported chains and the corresponding gas fees associated for transferring funds? 

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/near/docs/issues/2012
- [x] Create improved technical system design diagram (Multichain relayer)
- [ ] https://github.com/near/docs/issues/2013
- [ ] https://github.com/near/docs/issues/2014
- [ ] https://github.com/near/docs/issues/2158
- [ ] https://github.com/near/docs/issues/2159
- [ ] https://github.com/near/docs/issues/2160
- [ ] Update "Gas Station" article with mainnet address
```

**Comment by ravigautham** [comment]
@encody Hey Jacob, I just drafted this issue to improve the MC Gas Relayer docs for the upcoming mainnet launch in June. Let me know what you think about these improvements. 

cc @bucanero @gagdiez

**Comment by ravigautham** [comment]
Thanks adding your thoughts @encody! 

@thisisjoshford I think we can slot this issue for execution in the coming weeks.

**Comment by charleslavon** [comment]
@bucanero is there still work to be done here or can this be closed?

**Comment by ravigautham** [comment]
@thisisjoshford I'll be sharing a doc in the next couple days with some updates that we need to make

**Comment by ravigautham** [comment]
cc @anthony-near

**Comment by bucanero** [comment]
[Update notes for mainnet](https://docs.google.com/document/d/1ZfJECPe6xVuyI2bpQfYHAssF7Ck8fFvk7vjWwL9qwU0/edit)
