### ISSUE TITLE
[BUG] Tutorials are out of date

### ISSUE THREAD

**Issue by PiVortex** [near/docs#2006]
**Describe the bug** 🐞
The Zero to Hero tutorials in the docs (found [here](https://docs.near.org/tutorials/welcome)) and their respective repos are out of date; they use old tools, and the DevX could be vastly improved. 

**Expected behavior**
These tutorials and their respective repos should be updated to use new tools such as near-cli-rs, near-sdk-rs v5^ and follow newer practices. 

Tutorials to update.

https://docs.near.org/tutorials/nfts/js/introduction
https://docs.near.org/tutorials/nfts/introduction
https://docs.near.org/tutorials/fts/introduction
https://docs.near.org/tutorials/crosswords/basics/overview

It may be decided that these tutorials are no longer required with the current narrative (though I would disagree) and may instead be depreciated all together 

**Screenshots**
![image](https://github.com/near/docs/assets/124691791/3452d7bc-2178-4384-8ec1-a1ba98e6bd9c)

**Location** 🎯
https://docs.near.org/tutorials/welcome

```[tasklist]
### Tasks
- [ ] Update JS tutorial `/tutorials/nfts/js/introduction`
- [ ] https://github.com/near/docs/issues/2073
- [ ] https://github.com/near/docs/issues/2072
- [ ] https://github.com/near/docs/issues/2081
```
