### ISSUE TITLE
🔹[EPIC] Auction Series

### ISSUE THREAD

**Issue by gagdiez** [near/docs#2023]
We want to create a new series that takes the user from the start to the end of the NEAR development, teaching them about contract development, primitives, frontend integration and indexers.

For this, we came up with the idea of a simple Auction contract that gets iteratively updated adding more and more features:

1. An unlocked auction contract that gets funding and registers the winner
2. An auction contract, that has a beneficiary that can claim the money
3. An auction using FT
4. An auction using FTs that transfer an NFT to the winner of the auction

---

```[tasklist]
### Related Issues
- [x] Create the Rust series
- [x] Create the TS series
- [x] Build the frontend
- [x] Create the Indexer
- [x] Create the docs for it
```

### Resources
- Draft PR #2147

**Comment by PiVortex** [comment]
I have brought up a list of questions regarding this series here https://github.com/matiasbenary/auction-tutorial/issues/4
