### ISSUE TITLE
[META] restructure issues and pr templates based on best-in-class examples

### ISSUE THREAD

**Issue by amgando** [near/docs#210]
**Is your feature request related to a problem? Please describe.**
currently our issues (across all repos) are fine but they could be better

**Describe the solution you'd like**
these two examples are far superior: 
- they include multiple categories of issues (we have this, mostly)
- they include specific hints in the issues themselves on how to produce the kind of output that we need (ie. `near --version`, `node --version`, etc)
- they include outbound links for other kinds of support to encourage engagement (ie. Discord, StackOverflow, etc)

https://github.com/gatsbyjs/gatsby/issues/new/choose
https://github.com/hashicorp/terraform/issues/new/choose

**Comment by potatodepaulo** [comment]
Let's go with this format: https://github.com/microsoft/vscode/issues/new/choose.

Specifically, for the following repos
* [ ] near-shell
* [ ] near-api-js
* [ ] near-sdk-as
* [ ] near-sdk-rs
* [ ] create-near-app

Issues should all have three buttons on the "add new issue" page:
Bug, 
Feature, 
Question. 

Question can take them to the [near stack overflow](https://stackoverflow.com/questions/tagged/nearprotocol)

PRs should have a commented message thanking them for the contribution and then a note asking which issue this fixes.
