### ISSUE TITLE
[META] Update near-wallet.js to latest version on all examples

### ISSUE THREAD

**Issue by gagdiez** [near/docs#2208]
All our examples use the same `near-wallet` file that abstracts away the complexity of using the `near-wallet-selector`. We need to make sure all canonical examples have the methods used here: 

https://github.com/near/near-discovery/blob/develop/src/components/wallet-selector/WalletSelector.ts

Notice that in the examples we use Javascript and JSDocs 

- [x] Hello World: https://github.com/near-examples/hello-near-examples
- [x] Guest Book: https://github.com/near-examples/guest-book-examples
- [x] Counters: https://github.com/near-examples/counters
- [x] Coin Flip: https://github.com/near-examples/coin-flip-examples
- [x] Donations: https://github.com/near-examples/donation-examples
- [x] Multiple Contracts: https://github.com/near-examples/frontend-multiple-contracts
- etc

**Comment by PiVortex** [comment]
@gagdiez I think I should also add ethereum wallets to all examples, but I see you need this project ID. Did you set it up under a near account or your personal, we should probably have all the examples registered in the same place. https://docs.near.org/tools/ethereum-wallets#get-projectid
