### ISSUE TITLE
[DOC] Reusable moving forward component 

### ISSUE THREAD

**Issue by PiVortex** [near/docs#2282]
## What?

In many docs we have a "moving forward section" that often talks about where people can get support. This section should be easily updated in a single are that can then be propagated across docs.

## Why?

To improve maintainability of our docs and increase visibility of our support

## Acceptance Criteria

```[tasklist]
### Tasks
- [ ] Identify pages that should & should not have this content
- [ ] Determine the content that we want at the end of each section for devs to get help
- [ ] Update / create a new section that will be used and should be in one single location
```

## Resources
- Example https://docs.near.org/build/web3-apps/quickstart#moving-forward

**Comment by goffxnca** [comment]
i'm interested in working on this, could you assign it to me? 
 
saw you mentioned this section should be easy to update in one spot, but looks like there are a few variations of across different pages. maybe could craft a single standard texts or paragraph for this section and use it as a component? happy to build it out!


**[page1](https://docs.near.org/build/web3-apps/quickstart#moving-forward):**
> Moving Forward
> That's it for our quickstart tutorial. You have now seen a fully functional frontend that can talk with NEAR contracts and render Web3 components.
> 
> If you have any questions, do not hesitate in joining us on [Telegram](https://t.me/neardev) or [Discord](https://near.chat/). We regularly host Office Hours, in which you can join our voice channel and ask questions.
> 
> Happy coding!


**[page2](https://docs.near.org/tutorials/examples/xcc#moving-forward)**
> Moving Forward
> A nice way to learn is by trying to expand a contract. Modify the cross contract example to use the [guest-book](https://docs.near.org/tutorials/examples/guest-book) contract!. In this way, you can try to make a cross-contract call that attaches money. Remember to correctly [handle the callback](https://docs.near.org/build/smart-contracts/anatomy/crosscontract#callback-function), and to return the money to the user in case of error.

**[page3](https://docs.near.org/tutorials/examples/guest-book#moving-forward)**
> Moving Forward
> A nice way to learn is by trying to expand a contract. You can modify the guestbook example to incorporate a feature where users can give likes to messages. Additionally, implement a method to toggle the like.

**[page4](https://docs.near.org/tutorials/examples/count-near#moving-forward)**
> Moving Forward
> A nice way to learn is by trying to expand the contract. Modify it by adding a parameter to increment and decrement, so the user can choose by how much to change the value. For this, you will need to use knowledge from the [anatomy](https://docs.near.org/build/smart-contracts/anatomy/) and [storage](https://docs.near.org/build/smart-contracts/anatomy/storage) sections.

**[page5](https://docs.near.org/tutorials/examples/donation#moving-forward):**
> Moving Forward
> A nice way to learn is by trying to expand a contract. Modify the donation example so it accumulates the tokens in the contract instead of sending it immediately. Then, make a method that only the beneficiary can call to retrieve the tokens.

**[page6](https://docs.near.org/build/web3-apps/ai/ai-assistant#moving-forward):**
> Moving Forward
> That's it for the quickstart tutorial. You have now seen an open-source AI agent interacting with NEAR and controlling a wallet to make transactions.
> 
> To better understand how it works, check the [agent.py file](https://github.com/RezaRahemtola/near-ai-assistant/blob/main/ai/src/agent/agent.py) and the [Function Calling explanation on HuggingFace](https://huggingface.co/NousResearch/Hermes-2-Pro-Llama-3-8B#prompt-format-for-function-calling).
> 
> A lot of things could be built by leveraging this PoC, some ideas could be:
> 
> A chatbot integrated to the explorer to summarize transactions directly in the page
> Interactive tutorials in the documentation through a chatbot
> "How to create an NFT?"
> Multiple chats with explanations and code to complete given by the AI
> In the end, the AI publish the smart contract, mint an NFT and send it to you on testnet
> An AI trader reacting to on-chain or off-chain events to buy/sell some tokens with its wallet
> The only limit is your imagination!
> Happy coding! 🚀



**[page7](https://docs.near.org/build/smart-contracts/quickstart#moving-forward)**
> Moving Forward
> That's it for the quickstart tutorial. You have now seen a fully functional contract with a minimal user interface and testing.
> 
> To better understand the contract's structure, check our [contract's anatomy](https://docs.near.org/build/smart-contracts/anatomy/) page.
> 
> If you prefer to see more examples, check our [examples](https://docs.near.org/tutorials/examples/count-near) page.
> 
> Do not hesitate to reach out on [Discord](https://near.chat/) with any questions you have. We regularly host Office Hours, in which you can join our voice channel and ask questions.
> 
> Happy coding! 🚀

**Comment by gagdiez** [comment]
Hi @goffxnca , we love to see the people contributing to open source! 

docs is an open project where anyone can create PRs, so feel free to open one if you ever want to contribute

**Comment by PiVortex** [comment]
Hey @goffxnca - happy for you to contribute this! 

What we had in mind was one component that could be inserted anywhere relevant. As you have seen some next steps may be individual to a specific tutorial, I think these should remain but common info can be added to a component. 

Initial thoughts of what should be in the component is:
Link to dev telegram https://t.me/neardev
Discord https://discord.gg/nearprotocol
and that we have office hours at 11 AM UTC and 6PM UTC each Thursday on discord

**Comment by thisisjoshford** [comment]
> i'm interested in working on this, could you assign it to me?
> 
> saw you mentioned this section should be easy to update in one spot, but looks like there are a few variations across different pages. maybe could craft a single standard texts or paragraph for this section and use it as a component? happy to build it out!

Awesome @goffxnca ! I assigned you this ticket! TYSM!!!

As @PiVortex stated, creating a re-usable component that has clear instructions on how to get support is crucial. One issue we have is that there are MANY ways to get dev support through numerous channels. 

Currently we have a TG folder share link that has about 16 dev chats in it for separate areas of focus. See here:
https://t.me/addlist/VWPcqJDOmXdkZTQ5

Devs can find this folder by going to github.com/near and clicking on dev support at the top. Or at the bottom of sections there is a Dev Resources link that takes you here: https://docs.near.org/help and has what looks similar to a mirror of github.com/near (you created this right @bucanero ?)

In an ideal world, chain abstraction docs should link to the Chain abstraction telegram chat at the end of the article and so on for each topic that pertains to a specific channel. However, we could just link everyone to our main near devs TG channel or Discord as our two main points of entry and then direct support traffic from there.  A third option is to link to the folder of dev chats but that could be overwhelming to have 16 options (I'm also missing a few that I need admin rights to add)

So... before you start this @gagdiez @frol @bucanero can you chime in on what you think is best here?

I do think we could update the docs.near.org/help page to not just mirror github.com/near but have all the support channels listed (as we started) but include each TG channel and their area of focus with a link to each as well as the giant folder. Perhaps you could start there? I can create a new ticket for that if you like or update this one. Lmk what works best for you!

**Comment by thisisjoshford** [comment]
Cameron just shared this landing page for TG chats -> https://www.nearbuilders.com/

**Comment by goffxnca** [comment]
hey guys, thx for directions! loving the ideas about improving support channels and resources. i gonna start working on a reusable component with the basic discord, telegram and office hours info based on what’s been discussed so far. if the telegram link for the component changes later I can tweak it along.

My plans:
1. **build the new component** `SupportContact` (or better names if you’ve got one!) where it’ll include links to [discord](https://discord.gg/nearprotocol) [telegram](https://t.me/neardev) and office hours every thursday at 11 AM UTC and 6 PM UTC on discord.
2. **update those 7 pages**, here i’ll use the new `SupportContact` component in the `Moving Forward` sections across those 7 pages where the unique next steps for each article they stay as-is, here at the end of those unique steps, i’ll drop the new `SupportContact` to display general contact info.

pr is on its way soon, thoughts welcome.

**Comment by goffxnca** [comment]
hey @bucanero, thx for sharing thoughts! i’m a bit lost, does the planned reusable component for the moving forward sections still fit into what’s needed here, or would it end up overlapping with the broader `/help` solution you're working on? happy to adjust or step back if it’s already covered.

**Comment by bucanero** [comment]
> hey @bucanero, thx for sharing thoughts! i’m a bit lost, does the planned reusable component for the moving forward sections still fit into what’s needed here, or would it end up overlapping with the broader `/help` solution you're working on? happy to adjust or step back if it’s already covered.

hi @goffxnca ,

I'd say these are two things that are somewhat linked but can be done separately. I see that you just submitted a PR to add a reusable widget 👍 next if you want, and have a chance, feel free to add another PR addressing the comments about the `help` page that can be updated with support channels and Telegram links

**Comment by goffxnca** [comment]
hi @bucanero, thank you so much for reviewing and merging! I’ll continue working on the `help` page this weekend.
