### ISSUE TITLE
[Task] Move Out All Non-Maintained Frontend Frameworks

### ISSUE THREAD

**Issue by gagdiez** [near/docs#2391]
### Description

Our frontend section explains 3 things:

1. How to add `near-api-js` and `wallet-selector` to an existing JS App
2. How to use BOS to create and publish components
3. How to use `Chain hosted UI` to publish and use a website

Sadly enough, both `BOS` and `Chain Hosted UI` are no longer being maintained, and it does not look like anyone is going to be maintaining them in the short term

Having frameworks that are no longer maintained creates a bad user experience, since people invest time on trying it, only to discover that it is no longer working and nobody will ever fix it

---

## Acceptance Criteria

```[tasklist]
- [x] Remove relevant docs sections
- [x] Create a github page docs site for BOS, and move all docs there
- [x] Create a github page docs site for Chain UI, and move all docs there
- [x] Create an index page with relevant frontend gr
```

**Comment by flmel** [comment]
closed by #2416 
deprecated docs repo can be found here:
https://deprecated-near.github.io/legacy-docs/
