### ISSUE TITLE
[EPIC] add common contract functions with near-api-js

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#595]
Document common `near-api-js`  interactions with smart contracts

- [ ] add to a collection
- [ ] see if something is in a collection
- [ ] get from a collection
- [ ] remove from a collection
- [ ] make a cross-contract call
- [ ] make a cross-contract call and see if it succeeded
- [ ] make a cross-contract call and see if it succeeded and what the result was
- [ ] make a cross-contract call and see if it succeeded and what the result was and do a cross-contract call after that
- [ ] figure out who called the contract (signer/predecessor)
- [ ] do a factory deployment
- [ ] handle large numbers into methods as arguments
- [ ] return json formatted results
- [ ] return paginated results from a large collection
- [ ] accept deposits to payable methods
- [ ] make a "private" cross-contract call to ensure the promise succeeded
- [ ] "try catch finally" with promises
- [ ] initializing a contract
- [ ] upgrading a contract

**Comment by mikedotexe** [comment]
_mike added the `more-than-enhancement` label on Mar 18_

**Comment by thisisjoshford** [comment]
Closing this issue as we are enhancing NAJ documentation as well as refactoring the repo.
